
Post.create(title: "Led Zeppelin reedita 3 álbumes", text: "Led Zeppelin ha anunciado la reedición de los tres primeros lanzamientos de su proyecto de archivo")
Post.create(title: "The Killers estrena video", text: "The Killers acaba de estrenar el video musical de su último single 'Just Another Girl'")
Post.create(title: "Los Grammy homenajean", text: "Los premios Grammy conmemorará el 50 aniversario de la presentación histórica de los Beatles en el Show de Ed Sullivan")
Post.create(title: "David Bowie aparecen online", text: "'Atomica', 'The Informer', 'Like A Rocket Man' y 'Born In A UFO', es el título de cuatro nuevas canciones de David Bowie y que acaban de ver la luz en internet")
Post.create(title: "holaa")
Post.create(title: "Enrique Bunbury anuncia el lanzamiento", text: "Enrique Bunbury cumplió 46 años y aprovechó el festejo para revelar los datos de su esperado nuevo disco")

Tag.create(name: "Groupo")
Tag.create(name: "Solista")
Tag.create(name: "Led Zeppelin")
Tag.create(name: "The Killers")
Tag.create(name: "The Beatles")
Tag.create(name: "David Bowie")
Tag.create(name: "Grammy")
Tag.create(name: "Enrique Bunbury")

Connection.create(post_id: 1, tag_id: 3)
Connection.create(post_id: 1, tag_id: 1)
Connection.create(post_id: 2, tag_id: 1)
Connection.create(post_id: 2, tag_id: 4)
Connection.create(post_id: 3, tag_id: 7)
Connection.create(post_id: 3, tag_id: 5)
Connection.create(post_id: 4, tag_id: 2)
Connection.create(post_id: 4, tag_id: 6)
Connection.create(post_id: 5, tag_id: 2)
Connection.create(post_id: 5, tag_id: 8)
